// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// multiplier_bootstrap
arma::mat multiplier_bootstrap(arma::mat inf_func, int biters);
RcppExport SEXP _BMisc_multiplier_bootstrap(SEXP inf_funcSEXP, SEXP bitersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type inf_func(inf_funcSEXP);
    Rcpp::traits::input_parameter< int >::type biters(bitersSEXP);
    rcpp_result_gen = Rcpp::wrap(multiplier_bootstrap(inf_func, biters));
    return rcpp_result_gen;
END_RCPP
}
// multiplier_bootstrap_parallel
NumericMatrix multiplier_bootstrap_parallel(NumericMatrix inf_func, int biters);
RcppExport SEXP _BMisc_multiplier_bootstrap_parallel(SEXP inf_funcSEXP, SEXP bitersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type inf_func(inf_funcSEXP);
    Rcpp::traits::input_parameter< int >::type biters(bitersSEXP);
    rcpp_result_gen = Rcpp::wrap(multiplier_bootstrap_parallel(inf_func, biters));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BMisc_multiplier_bootstrap", (DL_FUNC) &_BMisc_multiplier_bootstrap, 2},
    {"_BMisc_multiplier_bootstrap_parallel", (DL_FUNC) &_BMisc_multiplier_bootstrap_parallel, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_BMisc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
