name: Reverse Dependency Check

on:
  workflow_dispatch:

jobs:
  revdep_check:
    runs-on: ubuntu-latest

    name: Reverse check ${{ inputs.which }} dependents

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfreetype6-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libpng-dev \
            libjpeg-dev \
            libtiff5-dev \
            gfortran \
            libblas-dev \
            liblapack-dev

      - name: Install R dependencies
        run: |
          Rscript -e "install.packages(c('remotes', 'revdepcheck', 'testthat'))"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"

      - name: Reverse Dependency Check
        run: |
          Rscript -e "
          rev_deps <- tools::package_dependencies(
            packages = 'BMisc',
            db = available.packages(),
            reverse = TRUE
          )
          rev_deps <- rev_deps[['BMisc']]
          cat('Testing the following reverse dependencies:', rev_deps, '\n')

          for (pkg in rev_deps) {
            cat('Installing and testing package:', pkg, '\n')
            tryCatch({
              install.packages(pkg, dependencies = TRUE)
              testthat::test_package(pkg)
            }, error = function(e) {
              cat('Error testing package:', pkg, '\n', e$message, '\n')
            })
          }
          "

      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Reverse-Dependency-Check-Results
          path: revdep/
